# ste_cos:egg/egg_find_tier2_page021
# Страница 22/27 широкого поиска. Абсолютные координаты от центра портала 0 66 0.
# schedule ОБНУЛЯЕТ execute-контекст между тиками, поэтому здесь всё через абсолютные
# координаты и явный селектор маркера, а не через @s/relative.

execute if block -13 72 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 72 -16
execute if block -13 72 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 72 16
execute if block -11 62 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 62 -18
execute if block -11 62 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 62 18
execute if block -11 70 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 70 -18
execute if block -11 70 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 70 18
execute if block -10 66 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 66 -19
execute if block -10 66 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 66 19
execute if block -8 60 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 60 -19
execute if block -8 60 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 60 19
execute if block -8 72 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 72 -19
execute if block -8 72 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 72 19
execute if block -6 61 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 61 -20
execute if block -6 61 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 61 20
execute if block -6 71 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 71 -20
execute if block -6 71 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 71 20
execute if block -5 60 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 60 -20
execute if block -5 60 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 60 20
execute if block -5 72 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 72 -20
execute if block -5 72 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 72 20
execute if block 5 60 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 60 -20
execute if block 5 60 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 60 20
execute if block 5 72 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 72 -20
execute if block 5 72 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 72 20
execute if block 6 61 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 61 -20
execute if block 6 61 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 61 20
execute if block 6 71 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 71 -20
execute if block 6 71 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 71 20
execute if block 8 60 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 60 -19
execute if block 8 60 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 60 19
execute if block 8 72 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 72 -19
execute if block 8 72 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 72 19
execute if block 10 66 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 66 -19
execute if block 10 66 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 66 19
execute if block 11 62 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 62 -18
execute if block 11 62 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 62 18
execute if block 11 70 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 70 -18
execute if block 11 70 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 70 18
execute if block 13 60 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 60 -16
execute if block 13 60 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 60 16
execute if block 13 72 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 72 -16
execute if block 13 72 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 72 16
execute if block 14 63 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 63 -16
execute if block 14 63 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 63 16
execute if block 14 69 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 69 -16
execute if block 14 69 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 69 16
execute if block 16 60 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 60 -13
execute if block 16 60 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 60 13
execute if block 16 63 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 63 -14
execute if block 16 63 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 63 14
execute if block 16 69 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 69 -14
execute if block 16 69 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 69 14
execute if block 16 72 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 72 -13
execute if block 16 72 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 72 13
execute if block 18 62 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 62 -11
execute if block 18 62 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 62 11
execute if block 18 70 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 70 -11
execute if block 18 70 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 70 11
execute if block 19 60 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 60 -8
execute if block 19 60 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 60 8
execute if block 19 66 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 66 -10
execute if block 19 66 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 66 10
execute if block 19 72 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 72 -8
execute if block 19 72 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 72 8
execute if block 20 60 -5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 60 -5
execute if block 20 60 5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 60 5
execute if block 20 61 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 61 -6
execute if block 20 61 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 61 6
execute if block 20 71 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 71 -6
execute if block 20 71 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 71 6
execute if block 20 72 -5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 72 -5
execute if block 20 72 5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 72 5
execute if block -19 65 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 65 -10
execute if block -19 65 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 65 10
execute if block -19 67 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 67 -10
execute if block -19 67 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 67 10
execute if block -17 64 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 64 -13
execute if block -17 64 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 64 13
execute if block -17 68 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 68 -13
execute if block -17 68 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 68 13
execute if block -13 64 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 64 -17
execute if block -13 64 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 64 17
execute if block -13 68 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 68 -17
execute if block -13 68 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 68 17
execute if block -10 65 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 65 -19
execute if block -10 65 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 65 19
execute if block -10 67 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 67 -19
execute if block -10 67 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 67 19
execute if block 10 65 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 65 -19
execute if block 10 65 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 65 19
execute if block 10 67 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 67 -19
execute if block 10 67 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 67 19
execute if block 13 64 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 64 -17
execute if block 13 64 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 64 17
execute if block 13 68 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 68 -17
execute if block 13 68 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 68 17
execute if block 17 64 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 64 -13
execute if block 17 64 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 64 13
execute if block 17 68 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 68 -13
execute if block 17 68 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 68 13
execute if block 19 65 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 65 -10
execute if block 19 65 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 65 10
execute if block 19 67 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 67 -10
execute if block 19 67 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 67 10
execute if block -20 66 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 66 -8
execute if block -20 66 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 66 8
execute if block -8 66 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 66 -20
execute if block -8 66 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 66 20
execute if block 8 66 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 66 -20
execute if block 8 66 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 66 20
execute if block 20 66 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 66 -8
execute if block 20 66 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 66 8
execute if block -20 59 -4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 59 -4
execute if block -20 59 4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 59 4
execute if block -20 62 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 62 -7
execute if block -20 62 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 62 7
execute if block -20 65 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 65 -8
execute if block -20 65 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 65 8
execute if block -20 67 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 67 -8
execute if block -20 67 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 67 8
execute if block -20 70 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 70 -7
execute if block -20 70 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 70 7
execute if block -20 73 -4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 73 -4
execute if block -20 73 4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 73 4
execute if block -19 64 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 64 -10
execute if block -19 64 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 64 10
execute if block -19 68 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 68 -10
execute if block -19 68 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 68 10
execute if block -10 64 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 64 -19
execute if block -10 64 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 64 19
execute if block -10 68 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 68 -19
execute if block -10 68 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 68 19
execute if block -8 65 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 65 -20
execute if block -8 65 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 65 20
execute if block -8 67 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 67 -20
execute if block -8 67 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 67 20
execute if block -7 62 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 62 -20
execute if block -7 62 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 62 20
execute if block -7 70 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 70 -20
execute if block -7 70 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 70 20
execute if block -4 59 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -4 59 -20
execute if block -4 59 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -4 59 20
execute if block -4 73 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -4 73 -20
execute if block -4 73 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -4 73 20
execute if block 4 59 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 4 59 -20
execute if block 4 59 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 4 59 20
execute if block 4 73 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 4 73 -20
execute if block 4 73 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 4 73 20
execute if block 7 62 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 62 -20
execute if block 7 62 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 62 20
execute if block 7 70 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 70 -20
execute if block 7 70 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 70 20
execute if block 8 65 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 65 -20
execute if block 8 65 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 65 20
execute if block 8 67 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 67 -20
execute if block 8 67 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 67 20
execute if block 10 64 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 64 -19
execute if block 10 64 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 64 19
execute if block 10 68 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 68 -19
execute if block 10 68 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 68 19
execute if block 19 64 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 64 -10
execute if block 19 64 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 64 10
execute if block 19 68 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 68 -10
execute if block 19 68 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 68 10
execute if block 20 59 -4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 59 -4
execute if block 20 59 4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 59 4
execute if block 20 62 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 62 -7
execute if block 20 62 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 62 7
execute if block 20 65 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 65 -8
execute if block 20 65 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 65 8
execute if block 20 67 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 67 -8
execute if block 20 67 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 67 8
execute if block 20 70 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 70 -7
execute if block 20 70 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 70 7
execute if block 20 73 -4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 73 -4
execute if block 20 73 4 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 73 4
execute if block -15 62 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 62 -15
execute if block -15 62 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 62 15
execute if block -15 70 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 70 -15
execute if block -15 70 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 70 15
execute if block 15 62 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 62 -15
execute if block 15 62 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 62 15
execute if block 15 70 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 70 -15
execute if block 15 70 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 70 15
execute if block -19 61 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 61 -9
execute if block -19 61 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 61 9
execute if block -19 71 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 71 -9
execute if block -19 71 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 71 9
execute if block -17 63 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 63 -13
execute if block -17 63 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 63 13
execute if block -17 69 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 69 -13
execute if block -17 69 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 69 13
execute if block -13 63 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 63 -17
execute if block -13 63 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 63 17
execute if block -13 69 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 69 -17
execute if block -13 69 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 69 17
execute if block -9 61 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 61 -19
execute if block -9 61 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 61 19
execute if block -9 71 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 71 -19
execute if block -9 71 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 71 19
execute if block 9 61 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 61 -19
execute if block 9 61 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 61 19
execute if block 9 71 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 71 -19
execute if block 9 71 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 71 19
execute if block 13 63 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 63 -17
execute if block 13 63 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 63 17
execute if block 13 69 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 69 -17
execute if block 13 69 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 69 17
execute if block 17 63 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 63 -13
execute if block 17 63 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 63 13
execute if block 17 69 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 69 -13
execute if block 17 69 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 69 13
execute if block 19 61 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 61 -9
execute if block 19 61 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 61 9
execute if block 19 71 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 71 -9
execute if block 19 71 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 71 9
execute if block -20 64 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 64 -8
execute if block -20 64 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 64 8
execute if block -20 68 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 68 -8
execute if block -20 68 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 68 8
execute if block -18 66 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 66 -12
execute if block -18 66 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 66 12
execute if block -16 62 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 62 -14
execute if block -16 62 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 62 14
execute if block -16 70 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 70 -14
execute if block -16 70 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 70 14
execute if block -14 62 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 62 -16
execute if block -14 62 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 62 16
execute if block -14 70 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 70 -16
execute if block -14 70 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 70 16
execute if block -12 66 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 66 -18
execute if block -12 66 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 66 18
execute if block -8 64 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 64 -20
execute if block -8 64 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 64 20
execute if block -8 68 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 68 -20
execute if block -8 68 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 68 20
execute if block 8 64 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 64 -20
execute if block 8 64 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 64 20
execute if block 8 68 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 68 -20
execute if block 8 68 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 68 20
execute if block 12 66 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 66 -18
execute if block 12 66 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 66 18
execute if block 14 62 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 62 -16
execute if block 14 62 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 62 16
execute if block 14 70 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 70 -16
execute if block 14 70 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 70 16
execute if block 16 62 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 62 -14
execute if block 16 62 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 62 14
execute if block 16 70 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 70 -14
execute if block 16 70 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 70 14
execute if block 18 66 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 66 -12
execute if block 18 66 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 66 12
execute if block 20 64 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 64 -8
execute if block 20 64 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 64 8
execute if block 20 68 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 68 -8
execute if block 20 68 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 68 8
execute if block -18 65 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 65 -12
execute if block -18 65 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 65 12
execute if block -18 67 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 67 -12
execute if block -18 67 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 67 12
execute if block -17 60 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 60 -12
execute if block -17 60 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 60 12
execute if block -17 72 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 72 -12
execute if block -17 72 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 72 12
execute if block -12 60 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 60 -17
execute if block -12 60 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 60 17
execute if block -12 65 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 65 -18
execute if block -12 65 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 65 18
execute if block -12 67 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 67 -18
execute if block -12 67 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 67 18
execute if block -12 72 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 72 -17
execute if block -12 72 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 72 17
execute if block 12 60 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 60 -17
execute if block 12 60 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 60 17
execute if block 12 65 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 65 -18
execute if block 12 65 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 65 18
execute if block 12 67 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 67 -18
execute if block 12 67 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 67 18
execute if block 12 72 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 72 -17
execute if block 12 72 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 72 17
execute if block 17 60 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 60 -12
execute if block 17 60 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 60 12
execute if block 17 72 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 72 -12
execute if block 17 72 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 72 12
execute if block 18 65 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 65 -12
execute if block 18 65 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 65 12
execute if block 18 67 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 67 -12
execute if block 18 67 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 67 12
execute if block -19 63 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 63 -10
execute if block -19 63 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 63 10
execute if block -19 69 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 69 -10
execute if block -19 69 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 69 10
execute if block -18 61 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 61 -11
execute if block -18 61 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 61 11
execute if block -18 71 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 71 -11
execute if block -18 71 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 71 11
execute if block -15 59 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 59 -14
execute if block -15 59 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 59 14
execute if block -15 73 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 73 -14
execute if block -15 73 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 73 14
execute if block -14 59 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 59 -15
execute if block -14 59 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 59 15
execute if block -14 73 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 73 -15
execute if block -14 73 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 73 15
execute if block -11 61 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 61 -18
execute if block -11 61 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 61 18
execute if block -11 71 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 71 -18
execute if block -11 71 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 71 18
execute if block -10 63 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 63 -19
execute if block -10 63 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 63 19
execute if block -10 69 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 69 -19
execute if block -10 69 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 69 19
execute if block 10 63 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 63 -19
execute if block 10 63 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 63 19
execute if block 10 69 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 69 -19
execute if block 10 69 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 69 19
execute if block 11 61 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 61 -18
execute if block 11 61 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 61 18
execute if block 11 71 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 71 -18
execute if block 11 71 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 71 18
execute if block 14 59 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 59 -15
execute if block 14 59 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 59 15
execute if block 14 73 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 73 -15
execute if block 14 73 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 73 15
execute if block 15 59 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 59 -14
execute if block 15 59 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 59 14
execute if block 15 73 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 73 -14
execute if block 15 73 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 73 14
execute if block 18 61 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 61 -11
execute if block 18 61 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 61 11
execute if block 18 71 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 71 -11
execute if block 18 71 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 71 11
execute if block 19 63 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 63 -10
execute if block 19 63 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 63 10
execute if block 19 69 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 69 -10
execute if block 19 69 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 69 10
execute if block -20 60 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 60 -6
execute if block -20 60 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 60 6
execute if block -20 72 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 72 -6
execute if block -20 72 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 72 6
execute if block -18 64 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 64 -12
execute if block -18 64 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 64 12
execute if block -18 68 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 68 -12
execute if block -18 68 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 68 12
execute if block -12 64 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 64 -18
execute if block -12 64 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 64 18
execute if block -12 68 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 68 -18
execute if block -12 68 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 68 18
execute if block -6 60 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 60 -20
execute if block -6 60 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 60 20
execute if block -6 72 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 72 -20
execute if block -6 72 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 72 20
execute if block 6 60 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 60 -20
execute if block 6 60 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 60 20
execute if block 6 72 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 72 -20
execute if block 6 72 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 72 20
execute if block 12 64 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 64 -18
execute if block 12 64 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 64 18
execute if block 12 68 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 68 -18
execute if block 12 68 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 68 18
execute if block 18 64 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 64 -12
execute if block 18 64 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 64 12
execute if block 18 68 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 68 -12
execute if block 18 68 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 68 12
execute if block 20 60 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 60 -6
execute if block 20 60 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 60 6
execute if block 20 72 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 72 -6
execute if block 20 72 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 72 6
execute if block -20 63 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 63 -8
execute if block -20 63 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 63 8
execute if block -20 69 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 69 -8
execute if block -20 69 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 69 8
execute if block -18 59 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 59 -10
execute if block -18 59 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 59 10
execute if block -18 73 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 73 -10
execute if block -18 73 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 73 10
execute if block -10 59 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 59 -18
execute if block -10 59 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 59 18
execute if block -10 73 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 73 -18
execute if block -10 73 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 73 18
execute if block -8 63 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 63 -20
execute if block -8 63 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 63 20
execute if block -8 69 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 69 -20
execute if block -8 69 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 69 20
execute if block 8 63 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 63 -20
execute if block 8 63 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 63 20
execute if block 8 69 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 69 -20
execute if block 8 69 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 69 20
execute if block 10 59 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 59 -18
execute if block 10 59 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 59 18
execute if block 10 73 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 73 -18
execute if block 10 73 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 73 18
execute if block 18 59 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 59 -10
execute if block 18 59 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 59 10
execute if block 18 73 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 73 -10
execute if block 18 73 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 73 10
execute if block 20 63 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 63 -8
execute if block 20 63 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 63 8
execute if block 20 69 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 69 -8
execute if block 20 69 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 69 8
execute if block -20 59 -5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 59 -5
execute if block -20 59 5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 59 5
execute if block -20 61 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 61 -7
execute if block -20 61 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 61 7
execute if block -20 71 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 71 -7
execute if block -20 71 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 71 7
execute if block -20 73 -5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 73 -5
execute if block -20 73 5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 73 5
execute if block -19 59 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 59 -8
execute if block -19 59 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 59 8
execute if block -19 73 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 73 -8
execute if block -19 73 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 73 8
execute if block -17 62 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 62 -13
execute if block -17 62 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 62 13
execute if block -17 70 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 70 -13
execute if block -17 70 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 70 13
execute if block -16 59 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 59 -13
execute if block -16 59 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 59 13
execute if block -16 73 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 73 -13
execute if block -16 73 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 73 13
execute if block -13 59 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 59 -16
execute if block -13 59 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 59 16
execute if block -13 62 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 62 -17
execute if block -13 62 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 62 17
execute if block -13 70 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 70 -17
execute if block -13 70 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 70 17
execute if block -13 73 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 73 -16
execute if block -13 73 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 73 16
execute if block -8 59 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 59 -19
execute if block -8 59 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 59 19
execute if block -8 73 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 73 -19
execute if block -8 73 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 73 19
execute if block -7 61 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 61 -20
execute if block -7 61 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 61 20
execute if block -7 71 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 71 -20
execute if block -7 71 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 71 20
execute if block -5 59 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 59 -20
execute if block -5 59 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 59 20
execute if block -5 73 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 73 -20
execute if block -5 73 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -5 73 20
execute if block 5 59 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 59 -20
execute if block 5 59 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 59 20
execute if block 5 73 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 73 -20
execute if block 5 73 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 5 73 20
execute if block 7 61 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 61 -20
execute if block 7 61 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 61 20
execute if block 7 71 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 71 -20
execute if block 7 71 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 71 20
execute if block 8 59 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 59 -19
execute if block 8 59 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 59 19
execute if block 8 73 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 73 -19
execute if block 8 73 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 73 19
execute if block 13 59 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 59 -16
execute if block 13 59 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 59 16
execute if block 13 62 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 62 -17
execute if block 13 62 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 62 17
execute if block 13 70 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 70 -17
execute if block 13 70 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 70 17
execute if block 13 73 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 73 -16
execute if block 13 73 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 73 16
execute if block 16 59 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 59 -13
execute if block 16 59 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 59 13
execute if block 16 73 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 73 -13
execute if block 16 73 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 73 13
execute if block 17 62 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 62 -13
execute if block 17 62 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 62 13
execute if block 17 70 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 70 -13
execute if block 17 70 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 70 13
execute if block 19 59 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 59 -8
execute if block 19 59 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 59 8
execute if block 19 73 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 73 -8
execute if block 19 73 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 73 8
execute if block 20 59 -5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 59 -5
execute if block 20 59 5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 59 5
execute if block 20 61 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 61 -7
execute if block 20 61 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 61 7
execute if block 20 71 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 71 -7
execute if block 20 71 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 71 7
execute if block 20 73 -5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 73 -5
execute if block 20 73 5 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 73 5
execute if block -15 61 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 61 -15
execute if block -15 61 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 61 15
execute if block -15 71 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 71 -15
execute if block -15 71 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 71 15
execute if block 15 61 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 61 -15
execute if block 15 61 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 61 15
execute if block 15 71 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 71 -15
execute if block 15 71 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 71 15
execute if block -19 62 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 62 -10
execute if block -19 62 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 62 10
execute if block -19 70 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 70 -10
execute if block -19 70 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 70 10
execute if block -18 63 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 63 -12
execute if block -18 63 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 63 12
execute if block -18 69 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 69 -12
execute if block -18 69 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 69 12
execute if block -16 61 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 61 -14
execute if block -16 61 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 61 14
execute if block -16 71 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 71 -14
execute if block -16 71 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 71 14
execute if block -14 61 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 61 -16
execute if block -14 61 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 61 16
execute if block -14 71 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 71 -16
execute if block -14 71 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 71 16
execute if block -12 63 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 63 -18
execute if block -12 63 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 63 18
execute if block -12 69 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 69 -18
execute if block -12 69 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 69 18
execute if block -10 62 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 62 -19
execute if block -10 62 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 62 19
execute if block -10 70 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 70 -19
execute if block -10 70 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -10 70 19
execute if block 10 62 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 62 -19
execute if block 10 62 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 62 19
execute if block 10 70 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 70 -19
execute if block 10 70 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 10 70 19
execute if block 12 63 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 63 -18
execute if block 12 63 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 63 18
execute if block 12 69 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 69 -18
execute if block 12 69 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 69 18
execute if block 14 61 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 61 -16
execute if block 14 61 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 61 16
execute if block 14 71 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 71 -16
execute if block 14 71 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 71 16
execute if block 16 61 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 61 -14
execute if block 16 61 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 61 14
execute if block 16 71 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 71 -14
execute if block 16 71 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 71 14
execute if block 18 63 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 63 -12
execute if block 18 63 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 63 12
execute if block 18 69 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 69 -12
execute if block 18 69 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 69 12
execute if block 19 62 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 62 -10
execute if block 19 62 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 62 10
execute if block 19 70 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 70 -10
execute if block 19 70 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 70 10
execute if block -19 60 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 60 -9
execute if block -19 60 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 60 9
execute if block -19 72 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 72 -9
execute if block -19 72 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 72 9
execute if block -9 60 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 60 -19
execute if block -9 60 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 60 19
execute if block -9 72 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 72 -19
execute if block -9 72 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 72 19
execute if block 9 60 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 60 -19
execute if block 9 60 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 60 19
execute if block 9 72 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 72 -19
execute if block 9 72 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 72 19
execute if block 19 60 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 60 -9
execute if block 19 60 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 60 9
execute if block 19 72 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 72 -9
execute if block 19 72 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 72 9
execute if block -20 62 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 62 -8
execute if block -20 62 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 62 8
execute if block -20 70 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 70 -8
execute if block -20 70 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 70 8
execute if block -8 62 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 62 -20
execute if block -8 62 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 62 20
execute if block -8 70 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 70 -20
execute if block -8 70 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -8 70 20
execute if block 8 62 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 62 -20
execute if block 8 62 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 62 20
execute if block 8 70 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 70 -20
execute if block 8 70 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 8 70 20
execute if block 20 62 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 62 -8
execute if block 20 62 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 62 8
execute if block 20 70 -8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 70 -8
execute if block 20 70 8 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 70 8
execute if block -20 66 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 66 -9
execute if block -20 66 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 66 9
execute if block -18 60 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 60 -11
execute if block -18 60 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 60 11
execute if block -18 72 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 72 -11
execute if block -18 72 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 72 11
execute if block -16 66 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 66 -15
execute if block -16 66 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 66 15
execute if block -15 66 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 66 -16
execute if block -15 66 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 66 16
execute if block -11 60 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 60 -18
execute if block -11 60 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 60 18
execute if block -11 72 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 72 -18
execute if block -11 72 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 72 18
execute if block -9 66 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 66 -20
execute if block -9 66 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 66 20
execute if block 9 66 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 66 -20
execute if block 9 66 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 66 20
execute if block 11 60 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 60 -18
execute if block 11 60 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 60 18
execute if block 11 72 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 72 -18
execute if block 11 72 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 72 18
execute if block 15 66 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 66 -16
execute if block 15 66 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 66 16
execute if block 16 66 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 66 -15
execute if block 16 66 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 66 15
execute if block 18 60 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 60 -11
execute if block 18 60 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 60 11
execute if block 18 72 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 72 -11
execute if block 18 72 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 72 11
execute if block 20 66 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 66 -9
execute if block 20 66 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 66 9
execute if block -20 65 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 65 -9
execute if block -20 65 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 65 9
execute if block -20 67 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 67 -9
execute if block -20 67 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 67 9
execute if block -19 66 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 66 -11
execute if block -19 66 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 66 11
execute if block -17 59 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 59 -12
execute if block -17 59 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 59 12
execute if block -17 73 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 73 -12
execute if block -17 73 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 73 12
execute if block -16 65 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 65 -15
execute if block -16 65 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 65 15
execute if block -16 67 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 67 -15
execute if block -16 67 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 67 15
execute if block -15 65 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 65 -16
execute if block -15 65 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 65 16
execute if block -15 67 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 67 -16
execute if block -15 67 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 67 16
execute if block -12 59 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 59 -17
execute if block -12 59 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 59 17
execute if block -12 73 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 73 -17
execute if block -12 73 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 73 17
execute if block -11 66 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 66 -19
execute if block -11 66 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 66 19
execute if block -9 65 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 65 -20
execute if block -9 65 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 65 20
execute if block -9 67 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 67 -20
execute if block -9 67 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 67 20
execute if block 9 65 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 65 -20
execute if block 9 65 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 65 20
execute if block 9 67 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 67 -20
execute if block 9 67 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 67 20
execute if block 11 66 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 66 -19
execute if block 11 66 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 66 19
execute if block 12 59 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 59 -17
execute if block 12 59 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 59 17
execute if block 12 73 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 73 -17
execute if block 12 73 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 73 17
execute if block 15 65 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 65 -16
execute if block 15 65 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 65 16
execute if block 15 67 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 67 -16
execute if block 15 67 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 67 16
execute if block 16 65 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 65 -15
execute if block 16 65 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 65 15
execute if block 16 67 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 67 -15
execute if block 16 67 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 67 15
execute if block 17 59 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 59 -12
execute if block 17 59 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 59 12
execute if block 17 73 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 73 -12
execute if block 17 73 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 73 12
execute if block 19 66 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 66 -11
execute if block 19 66 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 66 11
execute if block 20 65 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 65 -9
execute if block 20 65 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 65 9
execute if block 20 67 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 67 -9
execute if block 20 67 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 67 9
execute if block -19 65 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 65 -11
execute if block -19 65 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 65 11
execute if block -19 67 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 67 -11
execute if block -19 67 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 67 11
execute if block -17 61 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 61 -13
execute if block -17 61 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 61 13
execute if block -17 71 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 71 -13
execute if block -17 71 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 71 13
execute if block -13 61 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 61 -17
execute if block -13 61 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 61 17
execute if block -13 71 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 71 -17
execute if block -13 71 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -13 71 17
execute if block -11 65 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 65 -19
execute if block -11 65 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 65 19
execute if block -11 67 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 67 -19
execute if block -11 67 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 67 19
execute if block 11 65 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 65 -19
execute if block 11 65 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 65 19
execute if block 11 67 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 67 -19
execute if block 11 67 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 11 67 19
execute if block 13 61 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 61 -17
execute if block 13 61 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 61 17
execute if block 13 71 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 71 -17
execute if block 13 71 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 13 71 17
execute if block 17 61 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 61 -13
execute if block 17 61 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 61 13
execute if block 17 71 -13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 71 -13
execute if block 17 71 13 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 71 13
execute if block 19 65 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 65 -11
execute if block 19 65 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 65 11
execute if block 19 67 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 67 -11
execute if block 19 67 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 19 67 11
execute if block -18 62 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 62 -12
execute if block -18 62 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 62 12
execute if block -18 70 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 70 -12
execute if block -18 70 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -18 70 12
execute if block -12 62 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 62 -18
execute if block -12 62 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 62 18
execute if block -12 70 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 70 -18
execute if block -12 70 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -12 70 18
execute if block 12 62 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 62 -18
execute if block 12 62 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 62 18
execute if block 12 70 -18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 70 -18
execute if block 12 70 18 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 12 70 18
execute if block 18 62 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 62 -12
execute if block 18 62 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 62 12
execute if block 18 70 -12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 70 -12
execute if block 18 70 12 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 18 70 12
execute if block -20 59 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 59 -6
execute if block -20 59 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 59 6
execute if block -20 60 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 60 -7
execute if block -20 60 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 60 7
execute if block -20 64 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 64 -9
execute if block -20 64 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 64 9
execute if block -20 68 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 68 -9
execute if block -20 68 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 68 9
execute if block -20 72 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 72 -7
execute if block -20 72 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 72 7
execute if block -20 73 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 73 -6
execute if block -20 73 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -20 73 6
execute if block -17 66 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 66 -14
execute if block -17 66 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 66 14
execute if block -16 64 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 64 -15
execute if block -16 64 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 64 15
execute if block -16 68 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 68 -15
execute if block -16 68 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -16 68 15
execute if block -15 64 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 64 -16
execute if block -15 64 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 64 16
execute if block -15 68 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 68 -16
execute if block -15 68 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 68 16
execute if block -14 66 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 66 -17
execute if block -14 66 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 66 17
execute if block -9 64 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 64 -20
execute if block -9 64 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 64 20
execute if block -9 68 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 68 -20
execute if block -9 68 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -9 68 20
execute if block -7 60 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 60 -20
execute if block -7 60 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 60 20
execute if block -7 72 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 72 -20
execute if block -7 72 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -7 72 20
execute if block -6 59 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 59 -20
execute if block -6 59 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 59 20
execute if block -6 73 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 73 -20
execute if block -6 73 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -6 73 20
execute if block 6 59 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 59 -20
execute if block 6 59 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 59 20
execute if block 6 73 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 73 -20
execute if block 6 73 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 6 73 20
execute if block 7 60 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 60 -20
execute if block 7 60 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 60 20
execute if block 7 72 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 72 -20
execute if block 7 72 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 7 72 20
execute if block 9 64 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 64 -20
execute if block 9 64 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 64 20
execute if block 9 68 -20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 68 -20
execute if block 9 68 20 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 9 68 20
execute if block 14 66 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 66 -17
execute if block 14 66 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 14 66 17
execute if block 15 64 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 64 -16
execute if block 15 64 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 64 16
execute if block 15 68 -16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 68 -16
execute if block 15 68 16 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 15 68 16
execute if block 16 64 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 64 -15
execute if block 16 64 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 64 15
execute if block 16 68 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 68 -15
execute if block 16 68 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 16 68 15
execute if block 17 66 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 66 -14
execute if block 17 66 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 17 66 14
execute if block 20 59 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 59 -6
execute if block 20 59 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 59 6
execute if block 20 60 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 60 -7
execute if block 20 60 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 60 7
execute if block 20 64 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 64 -9
execute if block 20 64 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 64 9
execute if block 20 68 -9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 68 -9
execute if block 20 68 9 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 68 9
execute if block 20 72 -7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 72 -7
execute if block 20 72 7 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 72 7
execute if block 20 73 -6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 73 -6
execute if block 20 73 6 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] 20 73 6
execute if block -19 61 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 61 -10
execute if block -19 61 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 61 10
execute if block -19 64 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 64 -11
execute if block -19 64 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 64 11
execute if block -19 68 -11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 68 -11
execute if block -19 68 11 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 68 11
execute if block -19 71 -10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 71 -10
execute if block -19 71 10 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -19 71 10
execute if block -17 65 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 65 -14
execute if block -17 65 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 65 14
execute if block -17 67 -14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 67 -14
execute if block -17 67 14 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -17 67 14
execute if block -15 60 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 60 -15
execute if block -15 60 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 60 15
execute if block -15 72 -15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 72 -15
execute if block -15 72 15 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -15 72 15
execute if block -14 65 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 65 -17
execute if block -14 65 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 65 17
execute if block -14 67 -17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 67 -17
execute if block -14 67 17 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -14 67 17
execute if block -11 64 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 64 -19
execute if block -11 64 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 64 19
execute if block -11 68 -19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 68 -19
execute if block -11 68 19 minecraft:dragon_egg run return run tp @e[type=marker,tag=ste_cos_egg_tracker,limit=1] -11 68 19

schedule function ste_cos:egg/egg_find_tier2_page022 1t replace
